#!/usr/bin/env python3
"""
Integration tests for XMLDoc generation with <see> tag preservation.
"""

import sys
import tempfile
import xml.etree.ElementTree as ET
from pathlib import Path

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent.parent))

import pytest
from data_merger import DataMerger, TypeInfo, Property, Method, EnumMember
from generate_xmldoc import XMLDocGenerator, set_element_content


class TestSeeTagPreservation:
    """Tests for <see> tag preservation in XMLDoc output."""

    def test_set_element_content_with_see_tags(self):
        """Test that set_element_content preserves <see> tags."""
        # Create a test element
        parent = ET.Element('parent')

        # Content with <see> tags (as generated by Phase 03/04)
        content = 'This property uses <see cref="SolidWorks.Interop.sldworks.IModelDoc2">IModelDoc2</see> interface.'

        # Set the content
        set_element_content(parent, content)

        # Convert back to string to verify
        result = ET.tostring(parent, encoding='unicode')

        # Should contain actual <see> tags, not escaped
        assert '<see cref="SolidWorks.Interop.sldworks.IModelDoc2">' in result
        assert 'IModelDoc2</see>' in result
        assert '&lt;see' not in result  # Should NOT be escaped
        assert '&gt;' not in result  # Should NOT be escaped

    def test_set_element_content_with_multiple_see_tags(self):
        """Test content with multiple <see> tags."""
        parent = ET.Element('parent')

        content = '''This uses <see cref="SolidWorks.Interop.sldworks.IFeatureManager">IFeatureManager</see>
        and <see cref="SolidWorks.Interop.sldworks.IModelDoc2">IModelDoc2</see>.'''

        set_element_content(parent, content)
        result = ET.tostring(parent, encoding='unicode')

        # Both tags should be preserved
        assert '<see cref="SolidWorks.Interop.sldworks.IFeatureManager">' in result
        assert '<see cref="SolidWorks.Interop.sldworks.IModelDoc2">' in result
        assert result.count('<see cref=') == 2

    def test_set_element_content_plain_text(self):
        """Test plain text without XML tags."""
        parent = ET.Element('parent')

        content = 'This is just plain text with no XML tags.'

        set_element_content(parent, content)
        result = ET.tostring(parent, encoding='unicode')

        assert content in result
        assert '<see' not in result

    def test_set_element_content_with_mixed_content(self):
        """Test content with mixed text and tags."""
        parent = ET.Element('parent')

        content = 'Before <see cref="Type.Member">Member</see> middle text <see cref="Type2">Type2</see> after.'

        set_element_content(parent, content)
        result = ET.tostring(parent, encoding='unicode')

        # Check structure is preserved
        assert 'Before' in result
        assert 'middle text' in result
        assert 'after' in result
        assert '<see cref="Type.Member">Member</see>' in result

    def test_set_element_content_empty(self):
        """Test empty content."""
        parent = ET.Element('parent')
        set_element_content(parent, '')

        # Should have no text or children
        assert parent.text is None or parent.text == ''
        assert len(parent) == 0

    def test_set_element_content_with_newlines(self):
        """Test content with newlines (common in remarks)."""
        parent = ET.Element('parent')

        content = '''
First line with <see cref="Type1">Type1</see>.
Second line with <see cref="Type2">Type2</see>.
'''

        set_element_content(parent, content)
        result = ET.tostring(parent, encoding='unicode')

        # Newlines and tags should be preserved
        assert '<see cref="Type1">' in result
        assert '<see cref="Type2">' in result

    @pytest.fixture
    def temp_dir(self):
        """Create a temporary directory for test files."""
        with tempfile.TemporaryDirectory() as tmpdir:
            yield Path(tmpdir)

    @pytest.fixture
    def sample_types_xml_with_see_tags(self, temp_dir):
        """Create a sample type XML with <see> tags."""
        xml_content = """<?xml version="1.0"?>
<Types>
    <Type>
        <Name>ITestType</Name>
        <Assembly>TestAssembly</Assembly>
        <Namespace>Test.Namespace</Namespace>
        <Description><![CDATA[Test type that uses <see cref="Test.Namespace.IOtherType">IOtherType</see>.]]></Description>
        <Remarks><![CDATA[See also <see cref="Test.Namespace.IRelatedType">IRelatedType</see> for more information.]]></Remarks>
    </Type>
</Types>"""

        file_path = temp_dir / 'api_types.xml'
        file_path.write_text(xml_content, encoding='utf-8')
        return file_path

    def test_full_generation_preserves_see_tags(self, temp_dir, sample_types_xml_with_see_tags):
        """Test full XMLDoc generation preserves <see> tags."""
        # Create merger and load data
        merger = DataMerger()
        merger.load_api_types(sample_types_xml_with_see_tags)

        # Generate XMLDoc
        generator = XMLDocGenerator(
            output_dir=temp_dir,
            metadata_dir=temp_dir,
            verbose=False
        )

        output_files = generator.generate_all(merger)

        # Read the generated XML
        xml_file = output_files['TestAssembly']
        tree = ET.parse(xml_file)
        root = tree.getroot()

        # Convert to string
        xml_str = ET.tostring(root, encoding='unicode')

        # Verify <see> tags are preserved, not escaped
        assert '<see cref="Test.Namespace.IOtherType">IOtherType</see>' in xml_str
        assert '<see cref="Test.Namespace.IRelatedType">IRelatedType</see>' in xml_str

        # Verify they're NOT escaped
        assert '&lt;see' not in xml_str
        assert '&gt;' not in xml_str

    def test_enum_member_with_see_tags(self, temp_dir):
        """Test enum members with <see> tags in descriptions."""
        # Create enum XML with <see> tags
        xml_content = """<?xml version="1.0"?>
<EnumMembers>
    <Enum>
        <Name>TestEnum</Name>
        <Assembly>TestAssembly</Assembly>
        <Namespace>Test.Namespace</Namespace>
        <Members>
            <Member>
                <Name>Value1</Name>
                <Description><![CDATA[Use with <see cref="Test.Namespace.ITestType.Method">Method</see>]]></Description>
            </Member>
        </Members>
    </Enum>
</EnumMembers>"""

        enum_file = temp_dir / 'enum_members.xml'
        enum_file.write_text(xml_content, encoding='utf-8')

        # Load and generate
        merger = DataMerger()
        merger.load_enum_members(enum_file)

        generator = XMLDocGenerator(
            output_dir=temp_dir,
            metadata_dir=temp_dir,
            verbose=False
        )

        output_files = generator.generate_all(merger)

        # Read generated XML
        xml_file = output_files['TestAssembly']
        xml_str = xml_file.read_text(encoding='utf-8')

        # Verify <see> tag is preserved
        assert '<see cref="Test.Namespace.ITestType.Method">Method</see>' in xml_str
        assert '&lt;see' not in xml_str

    def test_invalid_xml_content_fallback(self):
        """Test that invalid XML falls back to text escaping."""
        parent = ET.Element('parent')

        # Content with unclosed tag (invalid XML)
        content = 'This has an <unclosed tag'

        set_element_content(parent, content)
        result = ET.tostring(parent, encoding='unicode')

        # Should be escaped since it's invalid XML
        assert '&lt;unclosed tag' in result or '<unclosed tag' in result
        # The important thing is it doesn't crash

    def test_complex_see_cref_attributes(self):
        """Test <see> tags with complex cref attributes."""
        parent = ET.Element('parent')

        # Complex method signature in cref
        content = 'Calls <see cref="System.String.Substring(System.Int32,System.Int32)">Substring</see> method.'

        set_element_content(parent, content)
        result = ET.tostring(parent, encoding='unicode')

        # Should preserve the full method signature
        assert 'System.String.Substring(System.Int32,System.Int32)' in result
        assert '<see cref=' in result


class TestExampleGeneration:
    """Tests for <example> element generation with C# code."""

    @pytest.fixture
    def temp_dir(self):
        """Create a temporary directory for test files."""
        with tempfile.TemporaryDirectory() as tmpdir:
            yield Path(tmpdir)

    @pytest.fixture
    def sample_types_with_examples(self, temp_dir):
        """Create sample type XML with example references."""
        xml_content = """<?xml version="1.0"?>
<Types>
    <Type>
        <Name>ITestType</Name>
        <Assembly>TestAssembly</Assembly>
        <Namespace>Test.Namespace</Namespace>
        <Description><![CDATA[Test type with examples.]]></Description>
        <Examples>
            <Example>
                <Name>Test Example</Name>
                <Language>C#</Language>
                <Url>testapi/Test_Example_CSharp.htm</Url>
            </Example>
            <Example>
                <Name>Test Example</Name>
                <Language>VBA</Language>
                <Url>testapi/Test_Example_VB.htm</Url>
            </Example>
        </Examples>
    </Type>
</Types>"""

        file_path = temp_dir / 'api_types.xml'
        file_path.write_text(xml_content, encoding='utf-8')
        return file_path

    @pytest.fixture
    def sample_examples_xml(self, temp_dir):
        """Create sample examples XML with C# code (mimics Phase 06 output with <code> tags)."""
        xml_content = """<?xml version="1.0"?>
<Examples>
    <Example>
        <Url>testapi/Test_Example_CSharp.htm</Url>
        <Content><![CDATA[Test Example Title
This is the example description.
<code>
using System;

public class TestExample
{
    public void Main()
    {
        // This is example C# code
        Console.WriteLine("Hello, World!");
    }
}
</code>]]></Content>
    </Example>
    <Example>
        <Url>testapi/Test_Example_VB.htm</Url>
        <Content><![CDATA[VBA Example Title
This is a VBA example.
<code>
' VBA Example
Sub Main()
    Debug.Print "Hello, World!"
End Sub
</code>]]></Content>
    </Example>
</Examples>"""

        file_path = temp_dir / 'examples.xml'
        file_path.write_text(xml_content, encoding='utf-8')
        return file_path

    def test_csharp_example_added(self, temp_dir, sample_types_with_examples, sample_examples_xml):
        """Test that C# examples are added to XMLDoc output."""
        # Load data
        merger = DataMerger()
        merger.load_api_types(sample_types_with_examples)
        merger.load_examples(sample_examples_xml)

        # Generate XMLDoc
        generator = XMLDocGenerator(
            output_dir=temp_dir,
            metadata_dir=temp_dir,
            verbose=False
        )

        output_files = generator.generate_all(merger)

        # Read generated XML as text to check CDATA and structure
        xml_file = output_files['TestAssembly']
        xml_content = xml_file.read_text(encoding='utf-8')

        # Verify CDATA section is present
        assert '<![CDATA[' in xml_content, "CDATA section not found"
        assert ']]>' in xml_content, "CDATA section not closed"

        # Verify NO double-nested <code> tags
        # Should NOT have: <code><![CDATA[...<code>...
        assert '<code><![CDATA[\n<code>' not in xml_content, "Double-nested code tags found!"
        assert '<code><![CDATA[<code>' not in xml_content, "Double-nested code tags found!"

        # Parse as XML tree
        tree = ET.parse(xml_file)
        root = tree.getroot()

        # Find the type member
        type_member = root.find(".//member[@name='T:Test.Namespace.ITestType']")
        assert type_member is not None, "Type member not found"

        # Check for example element
        example_elem = type_member.find('example')
        assert example_elem is not None, "No <example> element found"

        # Example should have text content (title/description) AND code child
        example_text = (example_elem.text or '').strip()
        assert example_text, "Example should have descriptive text"

        # Check for code element (child of example)
        code_elem = example_elem.find('code')
        assert code_elem is not None, "No <code> element found in example"

        # Verify C# code content is present (CDATA content gets read as text)
        code_text = code_elem.text or ''
        assert 'using System;' in code_text
        assert 'public class TestExample' in code_text
        assert 'Console.WriteLine' in code_text

        # Verify VBA code is NOT included (C# only)
        assert 'Debug.Print' not in xml_content
        assert 'VBA Example' not in xml_content

    def test_vba_examples_excluded(self, temp_dir, sample_types_with_examples, sample_examples_xml):
        """Test that non-C# examples are excluded."""
        # Load data
        merger = DataMerger()
        merger.load_api_types(sample_types_with_examples)
        merger.load_examples(sample_examples_xml)

        # Generate XMLDoc
        generator = XMLDocGenerator(
            output_dir=temp_dir,
            metadata_dir=temp_dir,
            verbose=False
        )

        output_files = generator.generate_all(merger)

        # Read generated XML
        xml_file = output_files['TestAssembly']
        xml_str = xml_file.read_text(encoding='utf-8')

        # Should have C# code
        assert 'Console.WriteLine' in xml_str

        # Should NOT have VBA code
        assert 'Debug.Print' not in xml_str

    def test_multiple_csharp_examples(self, temp_dir):
        """Test type with multiple C# examples."""
        # Create type with multiple C# examples
        types_xml = """<?xml version="1.0"?>
<Types>
    <Type>
        <Name>ITestType</Name>
        <Assembly>TestAssembly</Assembly>
        <Namespace>Test.Namespace</Namespace>
        <Description><![CDATA[Test type.]]></Description>
        <Examples>
            <Example>
                <Name>Example 1</Name>
                <Language>C#</Language>
                <Url>testapi/Example1_CSharp.htm</Url>
            </Example>
            <Example>
                <Name>Example 2</Name>
                <Language>C#</Language>
                <Url>testapi/Example2_CSharp.htm</Url>
            </Example>
        </Examples>
    </Type>
</Types>"""

        examples_xml = """<?xml version="1.0"?>
<Examples>
    <Example>
        <Url>testapi/Example1_CSharp.htm</Url>
        <Content><![CDATA[Example 1 Title
<code>
// Example 1
Console.WriteLine("Example 1");
</code>]]></Content>
    </Example>
    <Example>
        <Url>testapi/Example2_CSharp.htm</Url>
        <Content><![CDATA[Example 2 Title
<code>
// Example 2
Console.WriteLine("Example 2");
</code>]]></Content>
    </Example>
</Examples>"""

        types_file = temp_dir / 'types.xml'
        types_file.write_text(types_xml, encoding='utf-8')
        examples_file = temp_dir / 'examples.xml'
        examples_file.write_text(examples_xml, encoding='utf-8')

        # Load and generate
        merger = DataMerger()
        merger.load_api_types(types_file)
        merger.load_examples(examples_file)

        generator = XMLDocGenerator(
            output_dir=temp_dir,
            metadata_dir=temp_dir,
            verbose=False
        )

        output_files = generator.generate_all(merger)

        # Read generated XML
        xml_file = output_files['TestAssembly']
        tree = ET.parse(xml_file)
        root = tree.getroot()

        # Find the type member
        type_member = root.find(".//member[@name='T:Test.Namespace.ITestType']")

        # Should have two example elements
        example_elems = type_member.findall('example')
        assert len(example_elems) == 2, f"Expected 2 examples, found {len(example_elems)}"

        # Check both examples have code
        for example_elem in example_elems:
            code_elem = example_elem.find('code')
            assert code_elem is not None
            assert 'Console.WriteLine' in (code_elem.text or '')

    def test_example_statistics(self, temp_dir, sample_types_with_examples, sample_examples_xml):
        """Test that example statistics are tracked."""
        # Load data
        merger = DataMerger()
        merger.load_api_types(sample_types_with_examples)
        merger.load_examples(sample_examples_xml)

        # Generate XMLDoc
        generator = XMLDocGenerator(
            output_dir=temp_dir,
            metadata_dir=temp_dir,
            verbose=False
        )

        generator.generate_all(merger)

        # Check statistics
        assert generator.stats['types_with_examples'] == 1
        assert generator.stats['examples_added'] == 1  # Only C# example added

    def test_no_examples_when_content_missing(self, temp_dir):
        """Test that no example is added if content is not found."""
        # Create type with example reference
        types_xml = """<?xml version="1.0"?>
<Types>
    <Type>
        <Name>ITestType</Name>
        <Assembly>TestAssembly</Assembly>
        <Namespace>Test.Namespace</Namespace>
        <Examples>
            <Example>
                <Name>Missing Example</Name>
                <Language>C#</Language>
                <Url>testapi/Missing_CSharp.htm</Url>
            </Example>
        </Examples>
    </Type>
</Types>"""

        # Empty examples file (no content for the URL)
        examples_xml = """<?xml version="1.0"?>
<Examples>
</Examples>"""

        types_file = temp_dir / 'types.xml'
        types_file.write_text(types_xml, encoding='utf-8')
        examples_file = temp_dir / 'examples.xml'
        examples_file.write_text(examples_xml, encoding='utf-8')

        # Load and generate
        merger = DataMerger()
        merger.load_api_types(types_file)
        merger.load_examples(examples_file)

        generator = XMLDocGenerator(
            output_dir=temp_dir,
            metadata_dir=temp_dir,
            verbose=False
        )

        output_files = generator.generate_all(merger)

        # Read generated XML
        xml_file = output_files['TestAssembly']
        tree = ET.parse(xml_file)
        root = tree.getroot()

        # Find the type member
        type_member = root.find(".//member[@name='T:Test.Namespace.ITestType']")

        # Should have NO example elements (content not found)
        example_elems = type_member.findall('example')
        assert len(example_elems) == 0

        # Statistics should reflect this
        assert generator.stats['types_with_examples'] == 1  # Type has examples
        assert generator.stats['examples_added'] == 0  # But none were added

    def test_code_special_characters_not_escaped(self, temp_dir):
        """Test that special characters in code are not HTML-escaped."""
        # Create type with C# code containing <, >, &
        types_xml = """<?xml version="1.0"?>
<Types>
    <Type>
        <Name>ITestType</Name>
        <Assembly>TestAssembly</Assembly>
        <Namespace>Test.Namespace</Namespace>
        <Examples>
            <Example>
                <Name>Test Example</Name>
                <Language>C#</Language>
                <Url>testapi/Test_CSharp.htm</Url>
            </Example>
        </Examples>
    </Type>
</Types>"""

        examples_xml = """<?xml version="1.0"?>
<Examples>
    <Example>
        <Url>testapi/Test_CSharp.htm</Url>
        <Content><![CDATA[Special Characters Test
<code>
if (x < 10 && y > 5)
{
    List<string> items = new List<string>();
    string html = "<div>Test</div>";
}
</code>]]></Content>
    </Example>
</Examples>"""

        types_file = temp_dir / 'types.xml'
        types_file.write_text(types_xml, encoding='utf-8')
        examples_file = temp_dir / 'examples.xml'
        examples_file.write_text(examples_xml, encoding='utf-8')

        # Load and generate
        merger = DataMerger()
        merger.load_api_types(types_file)
        merger.load_examples(examples_file)

        generator = XMLDocGenerator(
            output_dir=temp_dir,
            metadata_dir=temp_dir,
            verbose=False
        )

        output_files = generator.generate_all(merger)

        # Read as text to check raw XML
        xml_file = output_files['TestAssembly']
        xml_content = xml_file.read_text(encoding='utf-8')

        # Code should be in CDATA section
        assert '<![CDATA[' in xml_content

        # Find the code section
        cdata_start = xml_content.find('<![CDATA[')
        cdata_end = xml_content.find(']]>', cdata_start)
        cdata_content = xml_content[cdata_start:cdata_end + 3]

        # Verify special characters are NOT escaped inside CDATA
        assert 'x < 10' in cdata_content  # < not escaped
        assert 'y > 5' in cdata_content   # > not escaped
        assert '&&' in cdata_content      # & not escaped
        assert 'List<string>' in cdata_content  # Generic < > not escaped
        assert '<div>Test</div>' in cdata_content  # HTML tags not escaped

        # Verify these are NOT escaped
        assert '&lt;' not in cdata_content
        assert '&gt;' not in cdata_content
        assert '&amp;&amp;' not in cdata_content


if __name__ == '__main__':
    pytest.main([__file__, '-v'])
